name: cd

on:
  push:
    branches: [ main ]
    paths: [ VERSION ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Version
      run: echo "::set-output name=version::$(cat VERSION)"
      id: get-version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::510771454635:role/GithubActions
        role-session-name: GithubActionsSession

    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: 510771454635.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push
      run: |
        docker build . -t 510771454635.dkr.ecr.us-east-1.amazonaws.com/lakitu:${{ steps.get-version.outputs.version }}
        docker push 510771454635.dkr.ecr.us-east-1.amazonaws.com/lakitu:${{ steps.get-version.outputs.version }}
